src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LocationRepository::class)
 */
class Location
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $etat;

    /**
     * @ORM\ManyToMany(targetEntity=Article::class, inversedBy="locations")
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="location")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    public function __construct()
    {
        $this->article = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticle(): Collection
    {
        return $this->article;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->article->contains($article)) {
            $this->article[] = $article;
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        $this->article->removeElement($article);

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Form/LocationType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Doctrine\ORM\EntityRepository;

class LocationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut', DateType::class, [
                'widget' => 'single_text',

                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5' => false,
            ])
            ->add('date_fin', DateType::class, [
                'widget' => 'single_text',

                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5' => false,
            ])
            ->add('article', EntityType::class, [
                'class' => Article::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->where('u.etat = :etat')
                        ->setParameter('etat', 'en_agence')
                        ->orderBy('u.libelle', 'ASC');
                },
                'choice_label' => 'libelle',
                'multiple' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Location::class,
        ]);
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Article;
use App\Repository\LocationRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class LocationController extends AbstractController
{
    /**
     * @Route("/locations", name="location_progess")
     * @Security("is_granted('IS_AUTHENTICATED_FULLY')")
     */
    public function index(LocationRepository $locationRepository): Response
    {
        $locations = $locationRepository->findBy(["etat" => "en_cours"]);

        return $this->render('location/index.html.twig', [
            'locations' => $locations,
        ]);
    }
}

templates/location/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Bien index
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h4 class="pull-left page-title">
        Locations
      </h4>
      <ol class="breadcrumb pull-right">
        <li><a href="/">Accueil</a></li>
        <li class="active">Locations</li>
      </ol>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-border panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Liste des location en cours
          </h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <div class="m-b-30 pull-right">
                <a href="" class="btn btn-primary waves-effect waves-light">
                  Créer <i class="fa fa-plus"></i>
                </a>
              </div>
            </div>
          </div>
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>
                  Id
                </th>
                <th>
                  Date début
                </th>
                <th>
                  Date fin
                </th>
                <th>
                  Client
                </th>
              </tr>
            </thead>
            <tbody>
              {% for location in locations %}
                <tr>
                  <td>
                    {{ location.id }}
                  </td>
                  <td>
                    {{ location.dateDebut|date('m/d/Y') }}
                  </td>
                  <td>
                    {{ location.dateFin|date('m/d/Y') }}
                  </td>
                  <td>
                    {{ location.client.user.prenom }} {{ location.client.user.nom }}
                  </td>
                </tr>
              {% else %}
                <tr>
                  <td colspan="100%">
                    no records found
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}