src/Entity/Bien.php
<?php

namespace App\Entity;

use App\Repository\BienRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BienRepository::class)
 */
class Bien
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $libelle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $centre_fiscal;

    /**
     * @ORM\ManyToOne(targetEntity=Proprietaire::class, inversedBy="biens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $proprietaire;

    /**
     * @ORM\ManyToOne(targetEntity=TypeBien::class, inversedBy="biens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_bien;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="bien", orphanRemoval=true)
     */
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCentreFiscal(): ?string
    {
        return $this->centre_fiscal;
    }

    public function setCentreFiscal(?string $centre_fiscal): self
    {
        $this->centre_fiscal = $centre_fiscal;

        return $this;
    }

    public function getProprietaire(): ?Proprietaire
    {
        return $this->proprietaire;
    }

    public function setProprietaire(?Proprietaire $proprietaire): self
    {
        $this->proprietaire = $proprietaire;

        return $this;
    }

    public function getTypeBien(): ?TypeBien
    {
        return $this->type_bien;
    }

    public function setTypeBien(?TypeBien $type_bien): self
    {
        $this->type_bien = $type_bien;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setBien($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getBien() === $this) {
                $article->setBien(null);
            }
        }

        return $this;
    }
}

src/Form/BienType.php
<?php

namespace App\Form;

use App\Entity\Bien;
use App\Entity\TypeBien;
use App\Entity\Proprietaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class BienType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle')
            ->add('adresse')
            ->add('centre_fiscal')
            ->add('proprietaire', EntityType::class, [
                // looks for choices from this entity
                'class' => Proprietaire::class,
                'choice_label' => 'user.prenom'
            ])
            ->add('type_bien', EntityType::class, [
                // looks for choices from this entity
                'class' => TypeBien::class,
                'choice_label' => 'libelle'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Bien::class,
        ]);
    }
}

src/Controller/BienController.php
<?php

namespace App\Controller;

use App\Entity\Bien;
use App\Entity\Article;
use App\Form\BienType;
use App\Form\ArticleType;
use App\Repository\BienRepository;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/bien")
 * @Security("is_granted('IS_AUTHENTICATED_FULLY')")
 */
class BienController extends AbstractController
{
    /**
     * @Route("/", name="bien_index", methods={"GET"})
     */
    public function index(BienRepository $bienRepository): Response
    {
        return $this->render('bien/index.html.twig', [
            'biens' => $bienRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="bien_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $bien = new Bien();
        $form = $this->createForm(BienType::class, $bien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bien);
            $entityManager->flush();

            return $this->redirectToRoute('bien_index');
        }

        return $this->render('bien/new.html.twig', [
            'bien' => $bien,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bien_show", methods={"GET"})
     */
    public function show(Bien $bien): Response
    {
        return $this->render('bien/show.html.twig', [
            'bien' => $bien,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="bien_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Bien $bien): Response
    {
        $form = $this->createForm(BienType::class, $bien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()
                ->getManager()
                ->flush();

            return $this->redirectToRoute('bien_index');
        }

        return $this->render('bien/edit.html.twig', [
            'bien' => $bien,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bien_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Bien $bien): Response
    {
        if (
            $this->isCsrfTokenValid(
                'delete' . $bien->getId(),
                $request->request->get('_token')
            )
        ) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bien);
            $entityManager->flush();
        }

        return $this->redirectToRoute('bien_index');
    }

    /**
     * @Route("/{id}/article", name="bien_article", methods={"GET", "POST"})
     */
    public function listArticle(ArticleRepository $articleRepository, Bien $bien): Response
    {
        $articles = $articleRepository->findBy(["bien" => $bien]);

        return $this->render('bien/articles.html.twig', [
            'bien' => $bien,
            'articles' => $articles,
        ]);
        
    }

    /**
     * @Route("/{id}/article/new", name="bien_new_article", methods={"GET", "POST"})
     */
    public function addArticle(Request $request, Bien $bien): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article->setBien($bien);
            $article->setEtat('en_agence');
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('bien_article', [
                'id' => $bien->getId(),
            ]);
        }

        return $this->render('bien/new_article.html.twig', [
            'bien' => $bien,
            'form' => $form->createView(),
        ]);
    }
}

templates/bien/_delete_form.html.twig
<form method="post" action="{{ path('bien_delete', {'id': bien.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bien.id) }}">
    <button class="btn btn-danger waves-effect waves-light">Delete</button>
</form>

templates/bien/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                {{ form_label(form.libelle, 'Nom du bien') }}
                {{ form_widget(form.libelle, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                {{ form_label(form.adresse, 'Adresse du bien') }}
                {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
         <div class="col-sm-6">
            <div class="form-group">
                {{ form_label(form.centre_fiscal, 'Centre iscal du bien') }}
                {{ form_widget(form.centre_fiscal, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                {{ form_label(form.proprietaire, 'Propriétaire') }}
                {{ form_widget(form.proprietaire, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                {{ form_label(form.type_bien, 'Type du bien') }}
                {{ form_widget(form.type_bien, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-sm-12">
            <button class="btn btn-primary btn-block waves-effect waves-light">{{ button_label|default('Enregistrer') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/bien/_form_article.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                {{ form_label(form.libelle, 'Nom article') }}
                {{ form_widget(form.libelle, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                {{ form_label(form.quantite, 'Quantité') }}
                {{ form_widget(form.quantite, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                {{ form_label(form.position, 'Position') }}
                {{ form_widget(form.position, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-sm-12">
            <button class="btn btn-primary btn-block waves-effect waves-light">{{ button_label|default('Enregistrer') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/bien/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles d'un bien{% endblock %}

{% block content %}
    


    <!-- Page-Title -->
  <div class="row">
    <div class="col-sm-12">
      <h4 class="pull-left page-title">
        Liste des articles du bien
      </h4>
      <ol class="breadcrumb pull-right">
        <li><a href="/">Accueil</a></li>
        <li><a href="{{ path('bien_index') }}">Biens</a></li>
        <li><a href="{{ path('bien_show', {'id': bien.id}) }}">Détail</a></li>
        <li class="active">Liste des articles</li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-border panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Formulaire d'un article pour un bien {{ bien.libelle }}
          </h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <div class="m-b-30 pull-right">
                <a href="{{ path('bien_new_article', {'id': bien.id}) }}"
                  class="btn btn-primary waves-effect waves-light">
                  Ajouter un bien <i class="fa fa-plus"></i>
                </a>
              </div>
            </div>
        </div>
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>
                Id
              </th>
              <th>
                Libelle
              </th>
              <th>
                Quantité
              </th>
              <th>
                Position
              </th>
            </tr>
          </thead>
          <tbody>
            {% for article in articles %}
              <tr>
                <td>
                  {{ article.id }}
                </td>
                <td>
                  {{ article.libelle }}
                </td>
                <td>
                  {{ article.quantite }}
                </td>
                <td>
                  {{ article.position }}
                </td>
              </tr>
            {% else %}
              <tr>
                <td colspan="100%">
                  no records found
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/bien/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Bien{% endblock %}

{% block content %}    

  <div class="row">
    <div class="col-sm-12">
      <h4 class="pull-left page-title">
        Modifier
      </h4>
      <ol class="breadcrumb pull-right">
        <li><a href="/">Accueil</a></li>
        <li><a href="{{ path('bien_index') }}">Biens</a></li>
        <li class="active">Modifier</li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-border panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Formulaire de modification du type de bien
          </h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <div class="m-b-30 pull-right">
                <a href="{{ path('bien_index') }}"
                  class="btn btn-primary waves-effect waves-light">
                  Voir la liste
                </a>
              </div>
            </div>
        </div>
        {{ include('bien/_form.html.twig', {'button_label': 'Modifier'}) }}
    </div>
</div>

{{ include('bien/_delete_form.html.twig') }}
{% endblock %}

templates/bien/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Bien index
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h4 class="pull-left page-title">
        Biens
      </h4>
      <ol class="breadcrumb pull-right">
        <li><a href="/">Accueil</a></li>
        <li class="active">Biens</li>
      </ol>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-border panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Liste des biens
          </h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <div class="m-b-30 pull-right">
                <a href="{{ path('bien_new') }}"
                  class="btn btn-primary waves-effect waves-light">
                  Créer <i class="fa fa-plus"></i>
                </a>
              </div>
            </div>
          </div>
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>
                  Id
                </th>
                <th>
                  Libelle
                </th>
                <th>
                  Adresse
                </th>
                <th>
                  Centre_fiscal
                </th>
                <th>
                  actions
                </th>
              </tr>
            </thead>
            <tbody>
              {% for bien in biens %}
                <tr>
                  <td>
                    {{ bien.id }}
                  </td>
                  <td>
                    {{ bien.libelle }}
                  </td>
                  <td>
                    {{ bien.adresse }}
                  </td>
                  <td>
                    {{ bien.centreFiscal }}
                  </td>
                  <td>
                    <div class="row">
                      <div class="col-sm-6">
                        <a class="btn btn-success waves-effect waves-light btn-block"
                          href="{{
                          path(
                            'bien_show',
                            {
                              id: bien.id
                            }
                          )
                          }}">
                          Voir
                        </a>
                      </div>
                      <div class="col-sm-6">
                        <a class="btn btn-info waves-effect waves-light btn-block"
                          href="{{
                          path(
                            'bien_edit',
                            {
                              id: bien.id
                            }
                          )
                          }}">
                          Modifier
                        </a>
                      </div>
                    </div>
                  </td>
                </tr>
              {% else %}
                <tr>
                  <td colspan="5">
                    no records found
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/bien/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Bien{% endblock %}

{% block content %}
    


    <!-- Page-Title -->
  <div class="row">
    <div class="col-sm-12">
      <h4 class="pull-left page-title">
        Créer
      </h4>
      <ol class="breadcrumb pull-right">
        <li><a href="/">Accueil</a></li>
        <li><a href="{{ path('bien_index') }}">Biens</a></li>
        <li class="active">Créer</li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-border panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Formulaire de création du bien
          </h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <div class="m-b-30 pull-right">
                <a href="{{ path('bien_index') }}"
                  class="btn btn-primary waves-effect waves-light">
                  Voir la liste
                </a>
              </div>
            </div>
        </div>
        {{ include('bien/_form.html.twig') }}
    </div>
</div>
{% endblock %}

templates/bien/new_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Bien{% endblock %}

{% block content %}
    


    <!-- Page-Title -->
  <div class="row">
    <div class="col-sm-12">
      <h4 class="pull-left page-title">
        Ajouter un article
      </h4>
      <ol class="breadcrumb pull-right">
        <li><a href="/">Accueil</a></li>
        <li><a href="{{ path('bien_index') }}">Biens</a></li>
        <li><a href="{{ path('bien_show', {'id': bien.id}) }}">Détail</a></li>
        <li class="active">Ajouter un article</li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-border panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Formulaire d'un article pour un bien {{ bien.libelle }}
          </h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <div class="m-b-30 pull-right">
                <a href="{{ path('bien_article', {'id': bien.id}) }}"
                  class="btn btn-primary waves-effect waves-light">
                  Voir la liste
                </a>
              </div>
            </div>
        </div>
        {{ include('bien/_form_article.html.twig') }}
    </div>
</div>
{% endblock %}

templates/bien/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bien{% endblock %}

{% block content %}

    <div class="row">
    <div class="col-sm-12">
      <h4 class="pull-left page-title">
        Détail
      </h4>
      <ol class="breadcrumb pull-right">
        <li><a href="/">Accueil</a></li>
        <li><a href="{{ path('bien_index') }}">Bien</a></li>
        <li class="active">Détail</li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-border panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Détail du Proprietaire
          </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6"></div>
                <div class="col-sm-6">
                <div class="m-b-30 pull-right">
                    <a href="{{ path('bien_index') }}"
                    class="btn btn-primary waves-effect waves-light">
                    Voir la liste
                    </a>
                </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-striped table-bordered">
                        <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ bien.id }}</td>
                            </tr>
                            <tr>
                                <th>Libelle</th>
                                <td>{{ bien.libelle }}</td>
                            </tr>
                            <tr>
                                <th>Adresse</th>
                                <td>{{ bien.adresse }}</td>
                            </tr>
                            <tr>
                                <th>Centre_fiscal</th>
                                <td>{{ bien.centreFiscal }}</td>
                            </tr>
                            <tr>
                                <th>Type du bien</th>
                                <td><span class="label label-default">{{ bien.typeBien.libelle }}</span></td>
                            </tr>
                            <tr>
                                <th>Proprietaire</th>
                                <td><span class="label label-info">{{ bien.proprietaire.user.prenom }} {{ bien.proprietaire.user.nom }}</span></td>
                            </tr>
                            <tr>
                                <th>Nombre d'articles</th>
                                <td>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a  href="{{ path('bien_article', {'id': bien.id}) }}">
                                                {{ bien.articles|length }}
                                            </a>
                                        </div>
                                        <div class="col-sm-6">
                                            <a class="btn btn-sm btn-warning pull-right" href="{{ path('bien_new_article', {'id': bien.id}) }}"><i class="fa fa-plus"></i></a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <a class="btn btn-primary btn-block waves-effect waves-light" href="{{ path('bien_edit', {'id': bien.id}) }}">Modifier</a>
                </div>
            </div>
        </div>
    </div>

    {{ include('bien/_delete_form.html.twig') }}
{% endblock %}